### ISSUE TITLE
Could you show us the project's BP?

### ISSUE THREAD

**Issue by matthewei** [metal3-io/ironic-standalone-operator#23]
Our team are very interested in this project and Could you show us the project's BP?

**Comment by dtantsur** [comment]
@matthewei I'm not sure what you mean under "BP", could you elaborate? You can always contact me on Slack, but please note: this project is in a very early stage. It's not ready for production yet.

**Comment by matthewei** [comment]
"BP" I mean "blueprint" I am very interested in this project and I want to verify it. If given the chance, I would like to contribute something to this project.

**Comment by dtantsur** [comment]
@matthewei one thing I wanna do is to write a formal proposal against metal3-docs. Otherwise, the closest I have is https://github.com/metal3-io/ironic-standalone-operator/blob/main/ARCHITECTURE.md.

If you want to help, the first and foremost work item is https://github.com/metal3-io/ironic-standalone-operator/issues/29. It's not my strongest area, so if you feel like you're up to the task - feel free to grab it.

**Comment by matthewei** [comment]
@dtantsur I will try it！

**Comment by matthewei** [comment]
@dtantsur This scripts are generated by `kubebuilder`. Why do you think we should modify it?

**Comment by matthewei** [comment]
I think we just finish `[baremetal-operator](https://github.com/matthewei/baremetal-operator/tree/main)
/ironic-deployment/ and we can use it.

**Comment by Rozzii** [comment]
Could we take this discussion to the slack channel @matthewei ? I can't really decide how to triage this issue ad the original question was answered by @dtantsur .
